#!/usr/bin/env bash

# This script should not be run as root.

# Want to have ~/Fiji.app be the canonical place Fiji is installed
cd

ZIP_FNAME="fiji-linux64.zip"
# This should be produced in the directory the unzip command below is called from
FIJI_DIR="Fiji.app"

# TODO TODO this .desktop file is actually NOT anywhere in the extracted download
# without some other step. is it generated by running fiji or did i create it myself?
# i don't think it was the latter...
# This should be (the only) *.desktop file (immediately) under Fiji.app directory
DESKTOP_BASENAME="ImageJ2.desktop"

# Link from https://imagej.net/software/fiji/downloads
wget https://downloads.imagej.net/fiji/latest/${ZIP_FNAME}
unzip ${ZIP_FNAME}
rm ${ZIP_FNAME}

# TODO TODO TODO figure out how to generate the .desktop file first

# TODO had i copied ImageJ2.desktop manually to ~/.local/share/applications at some
# point, or did some other step / use of ImageJ do that for me? either way, probably
# wouldn't hurt to copy it ourselves.
cp ${FIJI_DIR}/${DESKTOP_BASENAME} ${HOME}/.local/share/applications

# TODO TODO TODO set XDG_DATA_DIR (append line to bashrc if not set?) as i currently do
# in my atlas ~/.bashrc (though see comments there that there is probably a better place
# to set it...)

xdg-mime default ${DESKTOP_BASENAME} image/tiff

# If all want well, this command should give you the following output:
# $ xdg-mime query default image/tiff
# ImageJ2.desktop
# ...and double clicking TIFFs or `xdg-open <path/to/tiff>` should open the TIFF in Fiji
