---
- name: Installing postgresql apt packages
  apt:
    name: '{{ packages }}'
    update_cache: yes
  vars:
    packages:
    - postgresql
    - postgresql-contrib
  become: yes

- name: Setting up service so postgre starts on boot
  service:
    name: postgresql
    enabled: yes
  become: yes
